# This must be called before initialize
/remoll/setgeofile geometry/mollerMother.gdml

# This must be explicitly called
/run/initialize

# Field maps
/control/execute macros/load_magnetic_fieldmaps.mac

# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm

# Beam energy
/remoll/beamene 11 GeV


#/remoll/gen beam
/remoll/evgen/set moller
#/remoll/evgen/thcommin 30.0 deg
#/remoll/evgen/thcommax 150.0 deg
#/remoll/gen elastic 
#/remoll/evgen/emin 80.0 MeV
#/remoll/gen inelastic 
#/remoll/gen pion
#/remoll/piontype pi-
#/remoll/gen pion_LUND
#/remoll/gen inelasticAl
#/remoll/gen quasielasticAl
#/remoll/gen elasticAl

# Generation limits
# theta
/remoll/evgen/thmin 0.5 deg
/remoll/evgen/thmax 3.0 deg

# Beam current for rate
/remoll/beamcurr 85 microampere

# Make interactions with W, Cu, and Pb pure absorbers
/control/execute macros/kryptonite.mac

/remoll/seed 123456

# Output
/remoll/filename test_moller.root

# Shoot
/run/beamOn 100
