C units: length in m; energy,momentum,mass in GeV; angles in radians
      common /cophys/dpi,me,alpha,hbarc
      real me,alpha,hbarc
      double precision dpi
      integer nsites
      parameter (nsites=8)
      common /cotarg/Z,a,radlen,Aphonon,mospread,betaFF,ucell(3,nsites)
      real Z,a,radlen,Aphonon,mospread,betaFF,ucell
      common /cosetup/thx,thy,rotate(3,3),E,emitx,emity,spot,Erms,
     +                D,t,collim
      double precision thx,thy,rotate
      real E,emitx,emity,Erms,spot,D,t,collim
      common /coQ2list/q2points,q2theta2(1000),q2weight(1000)
      integer q2points
      real q2theta2,q2weight
