title: remoll
description: Simulations for the MOLLER Experiment at Jefferson Lab
baseurl: "/remoll"
github_username: jeffersonlab

# Build settings
theme: minima

# Start from README.md
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Markdown parser
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

header_pages: 
 - README.Running.md
 - geometry/README.md
 - macros/README.md
 - analysis/README.md
 - README.FAQ.md

# Settings
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

# Exclude from processing
exclude:
  - src
  - include
  - build
  - bin
  - lib
  - share
  - logfiles
  - rootfiles
  - Gemfile
  - Gemfile.lock

github: [metadata]
