# This must be called before initialize
/remoll/geometry/setfile geometry/mollerMother.gdml
/remoll/parallel/setfile geometry/mollerParallel.gdml 

# This must be explicitly called
/run/initialize

# Field maps
/control/execute macros/load_magnetic_fieldmaps.mac

# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm

# Beam energy
/remoll/beamene 11 GeV

# Beam generator
/remoll/evgen/set beam

# Beam current for rate
/remoll/beamcurr 85 microampere

# Seed
/remoll/seed 123456

# Output
/remoll/filename test_beam.root

# Shoot
/run/beamOn 100
