# This must be called before initialize
/remoll/setgeofile geometry/mollerMother.gdml

# This must be explicitly called
/run/initialize

# Field maps
/remoll/addfield map_directory/blockyHybrid_rm_3.0.txt
/remoll/addfield map_directory/blockyUpstream_rm_1.1.txt

# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm
# initial position
/remoll/beam_x0 10 mm
/remoll/beam_y0 10 mm
# initial angle
/remoll/beam_th0 10 mrad
/remoll/beam_ph0 10 mrad
# gaussian spread widths
/remoll/beam_dth 10 mrad
/remoll/beam_dph 10 mrad

# Beam energy
/remoll/beamene 11 GeV


#/remoll/evgen/set beam
/remoll/evgen/set moller
#/remoll/evgen/thcommin 30.0 deg
#/remoll/evgen/thcommax 150.0 deg
#/remoll/evgen/set elastic 
#/remoll/evgen/emin 80.0 MeV
#/remoll/evgen/set inelastic 
#/remoll/evgen/set pion
#/remoll/piontype pi-
#/remoll/evgen/set pion_LUND
#/remoll/evgen/set inelasticAl
#/remoll/evgen/set quasielasticAl
#/remoll/evgen/set elasticAl

# Generation limits
# theta
#/remoll/evgen/thmin 0.5 deg
#/remoll/evgen/thmax 3.0 deg
# phi
#/remoll/evgen/phmin -20.0 deg
#/remoll/evgen/phmax +20.0 deg

# Target positioning
#/remoll/targpos  10 cm
#/remoll/targlen 100 cm

# Beam current for rate
/remoll/beamcurr 85 microampere

# Make interactions with W, Cu, and Pb
# realistic rather than pure absorbers
/control/execute macros/kryptonite.mac

/remoll/seed 123456

# Output
/remoll/filename test_raster.root

# Shoot
/run/beamOn 1000
