# This must be called before initialize
/remoll/geometry/setfile geometry/mollerMother.gdml
/remoll/parallel/setfile geometry/mollerParallel.gdml 
/remoll/physlist/parallel/enable

# This must be explicitly called
/run/initialize

# Field maps
/control/execute macros/load_magnetic_fieldmaps.mac

# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm

# Beam energy
/remoll/beamene 11 GeV

#/remoll/evgen/set inelasticAl
#/remoll/evgen/set quasielasticAl
/remoll/evgen/set elasticAl

/remoll/targname DSAlTarg

# Generation limits
# theta
/remoll/evgen/thmin 0.5 deg
/remoll/evgen/thmax 3.0 deg

# Beam current for rate
/remoll/beamcurr 85 microampere

# Make interactions with W, Cu, and Pb
# realistic rather than pure absorbers
/control/execute macros/kryptonite.mac

/remoll/seed 123456

# Output
/remoll/filename test_elasticAl_DS.root

# Shoot
/run/beamOn 10000
