# This must be called before initialize
/remoll/setgeofile geometry_sculpt/mollerMother.gdml

# This must be explicitly called
/run/initialize

# Field maps
/remoll/addfield map_directory/blockyHybrid_rm_3.0.txt
/remoll/addfield map_directory/blockyUpstream_rm_1.1.txt

# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm

# Beam energy
/remoll/beamene 11 GeV

#/remoll/evgen/set inelasticAl
#/remoll/evgen/set quasielasticAl
/remoll/evgen/set elasticAl

# Generation limits
# theta
/remoll/thmin 0.5 deg
/remoll/thmax 3.0 deg

# Beam current for rate
/remoll/beamcurr 85 microampere

# Make interactions with W, Cu, and Pb
# realistic rather than pure absorbers
/remoll/kryptonite/set true

/remoll/seed 123456

# Output
/remoll/filename test_elasticAl.root

# Shoot
/run/beamOn 10000
