void moller_vs_hepmc()
{
  TChain Tmoller("T");
  Tmoller.Add("remollout_ee_ee_moller.root");

  TChain Thepmc("T");
  Thepmc.Add("remollout_ee_ee_hepmc.root");

  TCanvas c1("c1");
  c1.SetTitle("Comparison Moller and HepMC generated events");
  c1.Divide(2,2);
  c1.cd(1);
  Tmoller.Draw("part[0].th/deg >> hm(100,0,2)","ev.xs");
  gPad->SetLogy();
  c1.cd(2);
  Thepmc.Draw("part[0].th/deg >> hh(100,0,2)","ev.xs");
  gPad->SetLogy();
  c1.cd(3);
  TH1F* hm = (TH1F*) gDirectory->Get("hm");
  hm->GetXaxis()->SetTitle("Lab scattering angle #theta [deg]");
  hm->GetYaxis()->SetTitle("Cross section per bin [pb]");
  hm->SetLineColor(kBlue);
  TH1F* hh = (TH1F*) gDirectory->Get("hh");
  hh->GetXaxis()->SetTitle("Lab scattering angle #theta [deg]");
  hh->GetYaxis()->SetTitle("Cross section per bin [pb]");
  hh->SetLineColor(kRed);
  hm->Draw();
  hh->Draw("same");
  gPad->SetLogy();
  c1.cd(4);
  TH1F* hr = new TH1F(*hm);
  hr->Divide(hh, hm);
  hr->GetXaxis()->SetTitle("Lab scattering angle #theta [deg]");
  hr->GetYaxis()->SetTitle("Cross section ratio per bin");
  hr->Draw();
  gPad->SetLogy();
  c1.SaveAs("images/moller_vs_hepmc_xs.png");

  TCanvas c2("c2");
  c2.SetTitle("Comparison Moller and HepMC hits on det 28");
  c2.Divide(2,2);
  c2.cd(1);
  Tmoller.Draw("hit.r/mm >> hrme(150,0,1500)","rate * (hit.det == 28 && hit.pid == 11)");
  Tmoller.Draw("hit.r/mm >> hrmg(150,0,1500)","rate * (hit.det == 28 && hit.pid == 22)","same");
  gPad->SetLogy();
  c2.cd(2);
  Thepmc.Draw("hit.r/mm >> hrhe(150,0,1500)","rate * (hit.det == 28 && hit.pid == 11)");
  Thepmc.Draw("hit.r/mm >> hrhg(150,0,1500)","rate * (hit.det == 28 && hit.pid == 22)","same");
  gPad->SetLogy();
  c2.cd(3);
  TH1F* hrme = (TH1F*) gDirectory->Get("hrme");
  TH1F* hrmg = (TH1F*) gDirectory->Get("hrmg");
  hrme->GetXaxis()->SetTitle("Radius at virtual plane 28 [mm]");
  hrme->GetYaxis()->SetTitle("Rate per bin [Hz]");
  hrme->SetLineColor(kBlue);
  hrmg->GetXaxis()->SetTitle("Radius at virtual plane 28 [mm]");
  hrmg->GetYaxis()->SetTitle("Rate per bin [Hz]");
  hrmg->SetLineColor(kCyan);
  TH1F* hrhe = (TH1F*) gDirectory->Get("hrhe");
  TH1F* hrhg = (TH1F*) gDirectory->Get("hrhg");
  hrhe->GetXaxis()->SetTitle("Radius at virtual plane 28 [mm]");
  hrhe->GetYaxis()->SetTitle("Rate per bin [Hz]");
  hrhe->SetLineColor(kRed);
  hrhg->GetXaxis()->SetTitle("Radius at virtual plane 28 [mm]");
  hrhg->GetYaxis()->SetTitle("Rate per bin [Hz]");
  hrhg->SetLineColor(kMagenta);
  hrme->Draw();
  hrmg->Draw("same");
  hrhe->Draw("same");
  hrhg->Draw("same");
  gPad->SetLogy();
  c2.cd(4);
  TH1F* hrre = new TH1F(*hrme);
  TH1F* hrrg = new TH1F(*hrmg);
  hrre->Divide(hrhe, hrme);
  hrre->GetXaxis()->SetTitle("Radius at virtual plane 28 [mm]");
  hrre->GetYaxis()->SetTitle("Rate ratio per bin");
  hrre->SetLineColor(kBlack);
  hrrg->Divide(hrhg, hrmg);
  hrre->Draw();
  hrrg->Divide(hrhg, hrmg);
  hrrg->GetXaxis()->SetTitle("Radius at virtual plane 28 [mm]");
  hrrg->GetYaxis()->SetTitle("Rate ratio per bin");
  hrrg->SetLineColor(kGreen);
  hrrg->Draw("same");
  gPad->SetLogy();
  c2.SaveAs("images/moller_vs_hepmc_rates.png");

}
