#this will produce four files test_moller_$E.root, $E = 8,9,10,11 GeV.
/remoll/setgeofile geometry_sculpt/mollerMother.gdml
/run/initialize
# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm

/remoll/beamene 8 GeV

/remoll/gen beam

/remoll/targpos   0 cm
/remoll/targlen 150 cm
/remoll/beamcurr 85 microampere
/remoll/kryptonite true
/process/list
/remoll/seed 123456

/remoll/filename test_moller_8.root
/run/beamOn 100

/remoll/gen beam
/remoll/filename test_moller_9.root
/remoll/beamene 9 GeV
/run/beamOn 100

/remoll/gen beam
/remoll/filename test_moller_10.root
/remoll/beamene 10 GeV
/run/beamOn 100

/remoll/gen beam
/remoll/filename test_moller_11.root
/remoll/beamene 11 GeV
/run/beamOn 100
