/run/initialize

# Disable pion detectors
/remoll/SD/det_4001/enable no
/remoll/SD/det_4002/enable false
/remoll/SD/det_4003/enable false
/remoll/SD/det_4004/enable false
/remoll/filename test_det_enable_1.root
/run/beamOn 100

# Enable pion detectors
/remoll/SD/det_4001/enable
/remoll/SD/det_4002/enable yes
/remoll/SD/det_4003/enable yes
/remoll/SD/det_4004/enable true
/remoll/filename test_det_enable_2.root
/run/beamOn 100

# Print all detectors
/remoll/SD/print_all

# Disable all detectors
/remoll/SD/disable_all
/remoll/filename test_det_enable_3.root
/run/beamOn 100

# Enable all detectors
/remoll/SD/enable_all
/remoll/filename test_det_enable_4.root
/run/beamOn 100

# Disable range detectors
/remoll/SD/disable_range 4000 5000

# Enable range detectors
/remoll/SD/enable_range 4002 5000
