/remoll/geometry/setfile geometry/mollerMother.gdml
/remoll/parallel/setfile geometry/mollerParallel.gdml

/remoll/physlist/parallel/enable

/run/initialize

/remoll/addfield map_directory/blockyHybrid_rm_3.0.txt
/remoll/addfield map_directory/blockyUpstream_rm_1.1.txt

/control/execute macros/kryptonite.mac

/remoll/evgen/set hepmcAscii

/generator/hepmcAscii/open generators/MG5/ep/ep_ep/Events/run_01/unweighted_events.hepmc
/remoll/filename remollout_ep_ep.root
/run/beamOn 50000
