#  Example file

# store tracks
#/tracking/storeTrajectory 1

# This must be called before initialize
/remoll/geometry/setfile geometry/mollerMother.gdml
/remoll/parallel/setfile geometry/mollerParallel.gdml 

#/remoll/physlist/register QGSP_BERT_HP
/remoll/physlist/parallel/enable 

# This must be explicitly called
/run/initialize

/remoll/printgeometry true

/control/execute macros/load_magnetic_fieldmaps.mac

# Raster and initial angle stuff
/remoll/oldras true
/remoll/rasx 5 mm
/remoll/rasy 5 mm

/remoll/evgen/set moller
/remoll/evgen/beamPolarization +L
# /remoll/field/equationtype 2
# /remoll/field/steppertype 2
# /remoll/field/print

/remoll/beamene 11 GeV
/remoll/beamcurr 65 microampere

/remoll/SD/disable_all
# /remoll/SD/enable 28
# /remoll/SD/detect lowenergyneutral 28
# /remoll/SD/detect secondaries 28
# /remoll/SD/detect boundaryhits 28

/remoll/SD/enable_range 73001 73028
/remoll/SD/detect_range secondaries 73001 73028
/remoll/SD/detect_range boundaryhits 73001 73028

# /process/list

# Specify random number seed
/remoll/seed 123456

/remoll/filename remollout.root

#/tracking/verbose 2

#/remoll/printtargetinfo
/run/beamOn 1000
