# This must be called before initialize
/remoll/geometry/setfile geometry_sculpt/mollerMother.gdml

# Read geometry silently
/remoll/geometry/verbose 0

# Validate GDML and check for overlap while reading
/remoll/geometry/validate true
/remoll/geometry/overlapcheck true

# This must be explicitly called
/run/initialize

# Dump geometry and materials
/remoll/geometry/dumpelements
/remoll/geometry/dumpmaterials

# Dump geometry tree
/remoll/geometry/dumpgeometry true
