void anaVacuum(){
  // TFile *finV=TFile::Open("../output/remollout_VacTst_Moller_Vac.root","READ");
  // TFile *finC=TFile::Open("../output/remollout_VacTst_Moller_kryp_beamline_Can.root","READ");
  // TFile *finA=TFile::Open("../output/remollout_VacTst_Moller_kryp_beamline_Air.root","READ");
  // TFile *finC=TFile::Open("../output/remollout_VacTst_Moller_Can.root","READ");
  // TFile *finA=TFile::Open("../output/remollout_VacTst_Moller_Air.root","READ");

  TFile *finV=TFile::Open("../output/remollout_VacTst_epElastic_Vac.root","READ");
  TFile *finC=TFile::Open("../output/remollout_VacTst_epElastic_kryp_beamline_Can.root","READ");
  TFile *finA=TFile::Open("../output/remollout_VacTst_epElastic_kryp_beamline_Air.root","READ");
  // TFile *finC=TFile::Open("../output/remollout_VacTst_epElastic_beamline_Can.root","READ");
  // TFile *finA=TFile::Open("../output/remollout_VacTst_epElastic_beamline_Air.root","READ");
  // TFile *finC=TFile::Open("../output/remollout_VacTst_epElastic_Can.root","READ");
  // TFile *finA=TFile::Open("../output/remollout_VacTst_epElastic_Air.root","READ");

  // TFile *finV=TFile::Open("../output/remollout_VacTst_epInelastic_Vac.root","READ");
  // TFile *finC=TFile::Open("../output/remollout_VacTst_epInelastic_kryp_beamline_Can.root","READ");
  // TFile *finA=TFile::Open("../output/remollout_VacTst_epInelastic_kryp_beamline_Air.root","READ");
  // TFile *finC=TFile::Open("../output/remollout_VacTst_epInelastic_beamline_Can.root","READ");
  // TFile *finA=TFile::Open("../output/remollout_VacTst_epInelastic_beamline_Air.root","READ");
  // TFile *finC=TFile::Open("../output/remollout_VacTst_epInelastic_Can.root","READ");
  // TFile *finA=TFile::Open("../output/remollout_VacTst_epInelastic_Air.root","READ");

  TTree *tV=(TTree*)finV->Get("T");
  TTree *tC=(TTree*)finC->Get("T");
  TTree *tA=(TTree*)finA->Get("T");

  gStyle->SetOptStat("e");
  double zhigh=1e11;
  string tgtCuts="rate*(hit.e>0.001 && hit.det==28 && hit.pid==11 && hit.r>0.6 && hit.r<1.2 && hit.vz<1)";
  string NoNtgtCuts="rate*(hit.e>0.001 && hit.det==28 && hit.pid==11 && hit.r>0.6 && hit.r<1.2 && hit.vz>1)";
  string defaultCuts="rate*(hit.e>0.001 && hit.det==28 && hit.pid==11 && hit.r>0.6 && hit.r<1.2)";

  // string tgtCuts="rate*(hit.e>0.001 && hit.det==28 && hit.pid==11 && hit.r>0.935 && hit.r<1.1 && hit.vz<1)";
  // string NoNtgtCuts="rate*(hit.e>0.001 && hit.det==28 && hit.pid==11 && hit.r>0.935 && hit.r<1.1 && hit.vz>1)";
  // string defaultCuts="rate*(hit.e>0.001 && hit.det==28 && hit.pid==11 && hit.r>0.935 && hit.r<1.1)";

  TCanvas *c0=new TCanvas();
  TH1D *rateV = new TH1D("rateV","rate weighted dist",100,0.55,1.2);
  TH1D *rateA = new TH1D("rateA","rate weighted dist",100,0.55,1.2);
  TH1D *rateC = new TH1D("rateC","rate weighted dist",100,0.55,1.2);
  tV->Project("rateV","hit.r",defaultCuts.c_str());
  tA->Project("rateA","hit.r",defaultCuts.c_str());
  tC->Project("rateC","hit.r",defaultCuts.c_str());
  rateA->SetLineColor(2);
  rateV->SetLineColor(1);
  rateA->SetLineColor(2);
  rateC->SetLineColor(4);
  rateA->DrawCopy("h");
  rateV->DrawCopy("h&&same");
  rateC->DrawCopy("h&&same");
  gPad->SetLogy(1);

  TCanvas *c1=new TCanvas();
  c1->Divide(3);
  c1->cd(1);
  TH2D *xyPosV=new TH2D("xyPosV",";x;y",200,-1.2,1.2,200,-1.2,1.2);
  tV->Project("xyPosV","hit.y:hit.x",defaultCuts.c_str());
  xyPosV->GetZaxis()->SetRangeUser(1,zhigh);
  xyPosV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c1->cd(2);
  TH2D *xyPosC=new TH2D("xyPosC",";x;y",200,-1.2,1.2,200,-1.2,1.2);
  tC->Project("xyPosC","hit.y:hit.x",defaultCuts.c_str());
  xyPosC->GetZaxis()->SetRangeUser(1,zhigh);
  xyPosC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c1->cd(3);
  TH2D *xyPosA=new TH2D("xyPosA",";x;y",200,-1.2,1.2,200,-1.2,1.2);
  tA->Project("xyPosA","hit.y:hit.x",defaultCuts.c_str());
  xyPosA->GetZaxis()->SetRangeUser(1,zhigh);
  xyPosA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);

  TCanvas *c2=new TCanvas();
  c2->Divide(3);
  c2->cd(1);
  TH2D *xyMomV=new TH2D("xyMomV",";P_x;P_y",200,-0.5,0.5,200,-0.5,0.5);
  tV->Project("xyMomV","hit.py:hit.px",defaultCuts.c_str());
  xyMomV->GetZaxis()->SetRangeUser(1,zhigh);
  xyMomV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c2->cd(2);
  TH2D *xyMomC=new TH2D("xyMomC",";P_x;P_y",200,-0.5,0.5,200,-0.5,0.5);
  tC->Project("xyMomC","hit.py:hit.px",defaultCuts.c_str());
  xyMomC->GetZaxis()->SetRangeUser(1,zhigh);
  xyMomC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c2->cd(3);
  TH2D *xyMomA=new TH2D("xyMomA",";P_x;P_y",200,-0.5,0.5,200,-0.5,0.5);
  tA->Project("xyMomA","hit.py:hit.px",defaultCuts.c_str());
  xyMomA->GetZaxis()->SetRangeUser(1,zhigh);
  xyMomA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);

  TCanvas *c5=new TCanvas();
  c5->Divide(3);
  c5->cd(1);
  TH2D *erCorrV=new TH2D("erCorrV",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tV->Project("erCorrV","hit.e:hit.r",defaultCuts.c_str());
  erCorrV->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c5->cd(2);
  TH2D *erCorrC=new TH2D("erCorrC",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tC->Project("erCorrC","hit.e:hit.r",defaultCuts.c_str());
  erCorrC->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c5->cd(3);
  TH2D *erCorrA=new TH2D("erCorrA",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tA->Project("erCorrA","hit.e:hit.r",defaultCuts.c_str());
  erCorrA->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  TCanvas *c6=new TCanvas();
  TH2D *erCorrDiff=(TH2D*)erCorrA->Clone("e-r correlation difference");
  erCorrDiff->Add(erCorrV,-1);
  erCorrDiff->Rebin2D(4,4);
  erCorrDiff->DrawCopy("Surf3");

  TCanvas *c51=new TCanvas();
  c51->Divide(3);
  c51->cd(1);
  TH2D *erCorrTgtV=new TH2D("erCorrTgtV",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tV->Project("erCorrTgtV","hit.e:hit.r",tgtCuts.c_str());
  erCorrTgtV->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrTgtV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c51->cd(2);
  TH2D *erCorrTgtC=new TH2D("erCorrTgtC",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tC->Project("erCorrTgtC","hit.e:hit.r",tgtCuts.c_str());
  erCorrTgtC->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrTgtC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c51->cd(3);
  TH2D *erCorrTgtA=new TH2D("erCorrTgtA",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tA->Project("erCorrTgtA","hit.e:hit.r",tgtCuts.c_str());
  erCorrTgtA->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrTgtA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);

  TCanvas *c52=new TCanvas();
  c52->Divide(3);
  c52->cd(1);
  TH2D *erCorrNoNtgtV=new TH2D("erCorrNoNtgtV",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tV->Project("erCorrNoNtgtV","hit.e:hit.r",NoNtgtCuts.c_str());
  erCorrNoNtgtV->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrNoNtgtV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c52->cd(2);
  TH2D *erCorrNoNtgtC=new TH2D("erCorrNoNtgtC",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tC->Project("erCorrNoNtgtC","hit.e:hit.r",NoNtgtCuts.c_str());
  erCorrNoNtgtC->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrNoNtgtC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c52->cd(3);
  TH2D *erCorrNoNtgtA=new TH2D("erCorrNoNtgtA",";r[m];E[GeV]",200,0.5,1.3,200,0,12);
  tA->Project("erCorrNoNtgtA","hit.e:hit.r",NoNtgtCuts.c_str());
  erCorrNoNtgtA->GetZaxis()->SetRangeUser(1,zhigh);
  erCorrNoNtgtA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);

  TCanvas *c3=new TCanvas();
  TH1D *pV=new TH1D("pV",";momentum[GeV]",100,0,12);
  tV->Project("pV","hit.p",defaultCuts.c_str());
  TH1D *pA=new TH1D("pA",";momentum[GeV]",100,0,12);
  tA->Project("pA","hit.p",defaultCuts.c_str());
  TH1D *pC=new TH1D("pC",";momentum[GeV]",100,0,12);
  tC->Project("pC","hit.p",defaultCuts.c_str());
  pV->SetLineColor(1);
  pA->SetLineColor(2);
  pC->SetLineColor(4);
  pA->DrawCopy("h");
  pV->DrawCopy("h&&same");
  pC->DrawCopy("h&&same");
  gPad->SetLogy(1);

  TCanvas *c4=new TCanvas();
  TH1D *thV=new TH1D("thV",";theta [deg]",180,0,90);
  tV->Project("thV","acos(hit.pz/hit.p)*180/3.1415",defaultCuts.c_str());
  TH1D *thA=new TH1D("thA",";theta [deg]",180,0,90);
  tA->Project("thA","acos(hit.pz/hit.p)*180/3.1415",defaultCuts.c_str());
  TH1D *thC=new TH1D("thC",";theta [deg]",180,0,90);
  tC->Project("thC","acos(hit.pz/hit.p)*180/3.1415",defaultCuts.c_str());
  thV->SetLineColor(1);
  thA->SetLineColor(2);
  thC->SetLineColor(4);
  thA->DrawCopy("h");
  thV->DrawCopy("h&&same");
  thC->DrawCopy("h&&same");
  gPad->SetLogy(1);

  TCanvas *c41=new TCanvas();
  TH1D *thTgTV=new TH1D("thTgTV",";theta [deg]",180,0,90);
  tV->Project("thTgTV","acos(hit.pz/hit.p)*180/3.1415",tgtCuts.c_str());
  TH1D *thTgTA=new TH1D("thTgTA",";theta [deg]",180,0,90);
  tA->Project("thTgTA","acos(hit.pz/hit.p)*180/3.1415",tgtCuts.c_str());
  TH1D *thTgTC=new TH1D("thTgTC",";theta [deg]",180,0,90);
  tC->Project("thTgTC","acos(hit.pz/hit.p)*180/3.1415",tgtCuts.c_str());
  thTgTV->SetLineColor(1);
  thTgTA->SetLineColor(2);
  thTgTC->SetLineColor(4);
  thTgTA->DrawCopy("h");
  thTgTV->DrawCopy("h&&same");
  thTgTC->DrawCopy("h&&same");
  gPad->SetLogy(1);
  cout<<"Percent of contributions with tgt source(Vac): "<<thTgTV->Integral()/thV->Integral()<<endl;
  cout<<"Percent of contributions with tgt source(Air): "<<thTgTA->Integral()/thA->Integral()<<endl;
  cout<<"Percent of contributions with tgt source(Can): "<<thTgTC->Integral()/thC->Integral()<<endl;

  TCanvas *c42=new TCanvas();
  TH1D *thNoNtgtV=new TH1D("thNoNtgtV",";theta [deg]",180,0,90);
  tV->Project("thNoNtgtV","acos(hit.pz/hit.p)*180/3.1415",NoNtgtCuts.c_str());
  TH1D *thNoNtgtA=new TH1D("thNoNtgtA",";theta [deg]",180,0,90);
  tA->Project("thNoNtgtA","acos(hit.pz/hit.p)*180/3.1415",NoNtgtCuts.c_str());
  TH1D *thNoNtgtC=new TH1D("thNoNtgtC",";theta [deg]",180,0,90);
  tC->Project("thNoNtgtC","acos(hit.pz/hit.p)*180/3.1415",NoNtgtCuts.c_str());
  thNoNtgtV->SetLineColor(1);
  thNoNtgtA->SetLineColor(2);
  thNoNtgtC->SetLineColor(4);
  thNoNtgtA->DrawCopy("h");
  thNoNtgtV->DrawCopy("h&&same");
  thNoNtgtC->DrawCopy("h&&same");
  gPad->SetLogy(1);
  cout<<"Percent of contributions with non tgt source(Vac): "<<thNoNtgtV->Integral()/thV->Integral()
      <<"\tTotal rate compared to vacuum\t"<<thV->Integral()/thV->Integral()<<endl;
  cout<<"Percent of contributions with non tgt source(Air): "<<thNoNtgtA->Integral()/thA->Integral()
      <<"\tTotal rate compared to vacuum\t"<<thA->Integral()/thV->Integral()<<endl;
  cout<<"Percent of contributions with non tgt source(Can): "<<thNoNtgtC->Integral()/thC->Integral()
      <<"\tTotal rate compared to vacuum\t"<<thC->Integral()/thV->Integral()<<endl;

  TCanvas *c7=new TCanvas();
  c7->Divide(3);
  c7->cd(1);
  tV->Draw("hit.vy:hit.vx:hit.vz","rate*(hit.det==28 && hit.pid==11 && hit.r>0.6 && hit.r<1.2)");
  c7->cd(2);
  tC->Draw("hit.vy:hit.vx:hit.vz","rate*(hit.det==28 && hit.pid==11 && hit.r>0.6 && hit.r<1.2 && hit.vz>1)");
  c7->cd(3);
  tA->Draw("hit.vy:hit.vx:hit.vz","rate*(hit.det==28 && hit.pid==11 && hit.r>0.6 && hit.r<1.2 && hit.vz>1)");

  TCanvas *c8=new TCanvas();
  c8->Divide(3);
  c8->cd(1);
  TH2D *xzSrcV=new TH2D("xzSrcV",";z[m];x[m]",200,-1,30,200,-3,3);
  tV->Project("xzSrcV","hit.vx:hit.vz",defaultCuts.c_str());
  xzSrcV->GetZaxis()->SetRangeUser(1,zhigh);
  xzSrcV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c8->cd(2);
  TH2D *xzSrcC=new TH2D("xzSrcC",";z[m];x[m]",200,-1,30,200,-3,3);
  tC->Project("xzSrcC","hit.vx:hit.vz",defaultCuts.c_str());
  xzSrcC->GetZaxis()->SetRangeUser(1,zhigh);
  xzSrcC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c8->cd(3);
  TH2D *xzSrcA=new TH2D("xzSrcA",";z[m];x[m]",200,-1,30,200,-3,3);
  tA->Project("xzSrcA","hit.vx:hit.vz",defaultCuts.c_str());
  xzSrcA->GetZaxis()->SetRangeUser(1,zhigh);
  xzSrcA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);

  TCanvas *c9=new TCanvas();
  c9->Divide(3);
  c9->cd(1);
  TH2D *xySrcV=new TH2D("xySrcV",";x[m];y[m]",200,-3,3,200,-3,3);
  tV->Project("xySrcV","hit.vy:hit.vx",defaultCuts.c_str());
  xySrcV->GetZaxis()->SetRangeUser(1,zhigh);
  xySrcV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c9->cd(2);
  TH2D *xySrcC=new TH2D("xySrcC",";x[m];y[m]",200,-3,3,200,-3,3);
  tC->Project("xySrcC","hit.vy:hit.vx",defaultCuts.c_str());
  xySrcC->GetZaxis()->SetRangeUser(1,zhigh);
  xySrcC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c9->cd(3);
  TH2D *xySrcA=new TH2D("xySrcA",";x[m];y[m]",200,-3,3,200,-3,3);
  tA->Project("xySrcA","hit.vy:hit.vx",defaultCuts.c_str());
  xySrcA->GetZaxis()->SetRangeUser(1,zhigh);
  xySrcA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);

  TCanvas *c91=new TCanvas("c91","Full detector plane");
  c91->Divide(3);
  c91->cd(1);
  TH2D *rzSrcV=new TH2D("rzSrcV",";z[m];r[m]",200,-1,30,200,0,4);
  tV->Project("rzSrcV","sqrt(hit.vy*hit.vy + hit.vx*hit.vx):hit.vz",defaultCuts.c_str());
  rzSrcV->GetZaxis()->SetRangeUser(1,zhigh);
  rzSrcV->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c91->cd(2);
  TH2D *rzSrcC=new TH2D("rzSrcC",";z[m];r[m]",200,-1,30,200,0,4);
  tC->Project("rzSrcC","sqrt(hit.vy*hit.vy + hit.vx*hit.vx):hit.vz",defaultCuts.c_str());
  rzSrcC->GetZaxis()->SetRangeUser(1,zhigh);
  rzSrcC->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);
  c91->cd(3);
  TH2D *rzSrcA=new TH2D("rzSrcA",";z[m];r[m]",200,-1,30,200,0,4);
  tA->Project("rzSrcA","sqrt(hit.vy*hit.vy + hit.vx*hit.vx):hit.vz",defaultCuts.c_str());
  rzSrcA->GetZaxis()->SetRangeUser(1,zhigh);
  rzSrcA->DrawCopy("colz");
  gPad->SetLogz(1);
  gPad->SetGridx(1);
  gPad->SetGridy(1);

  TCanvas *c92=new TCanvas();
  TH1D *rSrcV=new TH1D("rSrcV",";source r [m]",100,-1,4);
  TH1D *rSrcC=new TH1D("rSrcC",";source r [m]",100,-1,4);
  TH1D *rSrcA=new TH1D("rSrcA",";source r [m]",100,-1,4);
  tV->Project("rSrcV","sqrt(hit.vy*hit.vy + hit.vx*hit.vx)",defaultCuts.c_str());
  tC->Project("rSrcC","sqrt(hit.vy*hit.vy + hit.vx*hit.vx)",defaultCuts.c_str());
  tA->Project("rSrcA","sqrt(hit.vy*hit.vy + hit.vx*hit.vx)",defaultCuts.c_str());
  rSrcV->SetLineColor(1);
  rSrcC->SetLineColor(4);
  rSrcA->SetLineColor(2);
  rSrcV->DrawCopy("h");
  rSrcC->DrawCopy("h&&same");
  rSrcA->DrawCopy("h&&same");

  TCanvas *c10=new TCanvas();
  TH1D *pTpV=new TH1D("pTpV",";pT [%]",100,0,1);
  tV->Project("pTpV","sqrt(hit.px*hit.px + hit.py*hit.py)",defaultCuts.c_str());
  TH1D *pTpA=new TH1D("pTpA",";pT [%]",100,0,1);
  tA->Project("pTpA","sqrt(hit.px*hit.px + hit.py*hit.py)",defaultCuts.c_str());
  TH1D *pTpC=new TH1D("pTpC",";pT [%]",100,0,1);
  tC->Project("pTpC","sqrt(hit.px*hit.px + hit.py*hit.py)",defaultCuts.c_str());
  pTpV->SetLineColor(1);
  pTpA->SetLineColor(2);
  pTpC->SetLineColor(4);
  pTpV->DrawCopy("h");
  pTpA->DrawCopy("h&&same");
  pTpC->DrawCopy("h&&same");
  gPad->SetLogy(1);

  TCanvas *c11=new TCanvas();
  TH1D *pTV=new TH1D("pTV",";pT [GeV]",100,0,12);
  tV->Project("pTV","hit.p*sqrt(hit.px*hit.px + hit.py*hit.py)",defaultCuts.c_str());
  TH1D *pTA=new TH1D("pTA",";pT [GeV]",100,0,12);
  tA->Project("pTA","hit.p*sqrt(hit.px*hit.px + hit.py*hit.py)",defaultCuts.c_str());
  TH1D *pTC=new TH1D("pTC",";pT [GeV]",100,0,12);
  tC->Project("pTC","hit.p*sqrt(hit.px*hit.px + hit.py*hit.py)",defaultCuts.c_str());
  pTV->SetLineColor(1);
  pTA->SetLineColor(2);
  pTC->SetLineColor(4);
  pTV->DrawCopy("h");
  pTA->DrawCopy("h&&same");
  pTC->DrawCopy("h&&same");
  gPad->SetLogy(1);


  // finV->Close();
  // finA->Close();
  // finC->Close();
}

