# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0  

/remoll/physlist/optical/enable

# This is the current working geometry
/remoll/setgeofile macros/issues/issue158/mollerMother_5open.gdml

/run/initialize

/remoll/beamene 855 MeV
/remoll/beamcurr 50 microampere
/control/execute vis/vis.mac

/remoll/evgen/set beam
/remoll/evgen/beam/px -0.0523
/remoll/evgen/beam/pz 0.9986 

/run/beamOn 1

