name: Build LCG on CVMFS

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_101/x86_64-ubuntu2004-gcc9-opt",
              "LCG_99/x86_64-ubuntu2004-gcc9-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v1
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          cmake -Bbuild -S.
          cmake --build build

  macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        LCG: ["LCG_101/x86_64-mac1015-clang120-opt",
              "LCG_99/x86_64-mac1015-clang120-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v1
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          cmake -Bbuild -S.
          cmake --build build
